spring:
  datasource:
    url: jdbc:mysql://localhost/lithium_changelog
    username: root
    password: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  cloud:
    stream:
      bindings:
        userattributestriggerinput :
          group: user-attributes-trigger-group-changelog
          binder : rabbit
          destination : userattributestriggerqueue

server:
  port: 9696
  
lithium:
  services:
    db:
      load-test-data: false

logging:
  level:
    lithium.service.changelog: INFO
